### PR TITLE
Fix #935: Upgrade to League Container 3.x. (Robo 3.x version)

### LINKED ISSUE #935: league/container 2.x is unmaintained and throws warnings on composer install
### Steps to reproduce
Run `composer install` on any project using any version of Robo.

### Expected behavior
No warnings.

### Actual behavior
Deprecation warning:
> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

This warning occurs because Robo depends on `"league/container": "^2.4.1",`, and league/container 2.x versions depend on the abandoned container-interop.

Additionally, league/container 2.x is [explicitly no longer supported](https://container.thephpleague.com/) as of over a year ago.

Robo should upgrade league/container to 3.x in order to fix this.

### PR DESCRIPTION
**Pull request by joeparsons**
### Overview
This pull request:

- [x] Fixes a bug
- [x] Adds a feature
- [x] Breaks backwards compatibility
- [ ] Has tests that cover changes
- [ ] Adds or fixes documentation

### Summary
League Container 2.x is unmaintained and throws warnings when users install Robo. Robo needs to upgrade to League Container 3.x.

This includes @danepowell's changes from #955 (modified so they apply cleanly to the Robo 3.x branch) and an additional change to `Robo\Runner` to handle the exceptions now thrown by [League\Container\ContainerAwareTrait::getContainer()](https://github.com/thephpleague/container/blob/3.3.1/src/ContainerAwareTrait.php#L34-L46)

### Description
3.x tests pass locally for me with these changes.

### CODE REVIEW

File: src/Collection/CollectionBuilder.php [hunk 1]
```diff
@@ -83,7 +83,7 @@ public function __construct($commandFile)
     }
 
     /**
-     * @param \League\Container\ContainerInterface $container
+     * @param \League\Container\Container $container
```
Comment (greg-1-anderson) [inline src/Collection/CollectionBuilder.php]: Shouldn't all of these references to ContainerInterface become Psr\Container\ContainerInterface?

Comment (joeparsons) [reply src/Collection/CollectionBuilder.php]: I was thinking that and even made that change in a local branch based on 2.x at one point but wasn't totally sure since Robo uses some `League\Container` specific features.  I'll try making that change to this branch now.

File: src/Robo.php [hunk 2]
```diff
@@ -139,7 +139,7 @@ public static function loadConfiguration($paths, $config = null)
      * @param null|\Consolidation\Config\ConfigInterface $config
      * @param null|\Composer\Autoload\ClassLoader $classLoader
      *
-     * @return \Psr\Container\ContainerInterface
+     * @return \League\Container\Container|\Psr\Container\ContainerInterface
```
Comment (greg-1-anderson) [inline src/Robo.php]: \League\Container\Container **isa** \Psr\Container\ContainerInterface, so it seems unnecessary to explicitly list it as a return type.

**Comment by greg-1-anderson** [comment]
LGTM, thanks for the upgrade.
