### PR TITLE
Fix PHP error in Minify

### LINKED ISSUE #254: Undefined offset while minifying files
Hi. I'm iterating over a folder and minifying all the JavaScript files in it. The problem I'm having is that some of the files have already been minified. When Robo tries to minify them, I get this error.

```
PHP Notice:  Undefined offset: -9223372036854775808 in vendor/codegyre/robo/src/Common/TaskIO.php on line 33
PHP Stack trace:
PHP   1. {main}() vendor/codegyre/robo/robo:0
PHP   2. Robo\Runner->execute() vendor/codegyre/robo/robo:19
PHP   3. Symfony\Component\Console\Application->run() vendor/codegyre/robo/src/Runner.php:87
PHP   4. Symfony\Component\Console\Application->doRun() vendor/symfony/console/Application.php:123
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Application.php:192
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Application.php:840
PHP   7. call_user_func() vendor/symfony/console/Command/Command.php:257
PHP   8. Robo\Application->Robo\{closure}() vendor/symfony/console/Command/Command.php:257
PHP   9. call_user_func_array() vendor/codegyre/robo/src/Application.php:32
PHP  10. RoboFile->runMinifyJavaScript() vendor/codegyre/robo/src/Application.php:32
PHP  11. Robo\Task\Assets\Minify->run() RoboFile.php:82
PHP  12. Robo\Task\BaseTask->formatBytes() vendor/codegyre/robo/src/Task/Assets/Minify.php:270
```

Obviously, trying to minify those files again isn't ideal, but it seems strange that it would cause this PHP error.

Thanks.

### PR DESCRIPTION
**Pull request by jjok**
### Overview
This pull request:

- [X] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [X] Needs tests

### Summary

Fixes #254.

### Description

If the minified size of a file was greater than the original size a PHP
error would be thrown. This would happen if you tried to minifed files
that had already been minifed.
This fix stops the minifed size being greater than the original size.

### CODE REVIEW

File: src/Task/Assets/Minify.php [hunk 1]
```diff
@@ -263,7 +263,7 @@ public function run()
             return Result::error($this, 'Minification failed.');
         }
 
-        $size_after = strlen($minified);
+        $size_after = min($size_before, strlen($minified));
         $dst = $this->dst . '.part';
         $write_result = file_put_contents($dst, $minified);
```
Comment (jjok) [inline src/Task/Assets/Minify.php]: OK. I'll make that change.

**Comment by greg-1-anderson** [comment]
Tests would be nice, but since this fixes a bug, and there aren't existing tests, I'm going to merge it as-is.  Thanks.

**Comment by jjok** [comment]
Yeah, I would've done tests if there already were some. I'll see if I can do that, at some point.

**Comment by greg-1-anderson** [comment]
Take a look at some of the existing tests for other tasks, and see if that helps. Appreciated, if you have time.
